name: hydro
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - xarray
  - pandas
  - ipykernel
  - ca-certificates
  - openssl
  - netcdf4
  - scipy
  - matplotlib
  - certifi
  - seaborn
  - salem
  - shapely
  - geopandas
  - rasterio
  - dask
  - openpyxl
  - pwlf

  - pip
  - pip:
    - git+https://github.com/luna-bloin/bias_correction.git
