name: CESM2energy
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - numpy
  - python
  - salem
  - geopandas
  - rasterio
  - nc-time-axis
  - bias_correction
  - tqdm
  - windpowerlib
  - gsee
